### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by domaingood**
Zulip Need to update

### CODE REVIEW

**Comment by indigoxela** [comment]
@domaingood Many thanks for providing a PR. Which issue is related to this?

**Comment by BWPanda** [comment]
@domaingood Thanks! As @indigoxela alluded to, all PRs need a corresponding issue. If you can create one just stating what the issue is and link to this PR, we can review and merge.

**Comment by domaingood** [comment]
https://github.com/domaingood/backdrop-issues/tree/patch-1
I added https://backdrop.zulipchat.com/ 
Backdrop now using Zulip so I replace gitter.

Thank you

**Comment by indigoxela** [comment]
@domaingood I created the [Issue](https://github.com/backdrop/backdrop-issues/issues/4731) we need for this. :wink:

**Pull request merged**
